// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbuegumluulltutadsyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idWVndW1sdXVsbHR1dGFkc3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTY3ODMsImV4cCI6MjA1OTI5Mjc4M30.lWr7TAmm-WexEw9O-uOqyuRJWW0BMsPtMAWUcy_Cvxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);